name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ] # Se activa cuando subes algo a la rama main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jeremyleonel/jeremyweb2026:latest
